-- Create PredefinedWorker table
CREATE TABLE IF NOT EXISTS "PredefinedWorker" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create unique index for worker names
CREATE UNIQUE INDEX IF NOT EXISTS "PredefinedWorker_name_key" ON "PredefinedWorker"("name");

-- Create PredefinedCompany table
CREATE TABLE IF NOT EXISTS "PredefinedCompany" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create unique index for company names
CREATE UNIQUE INDEX IF NOT EXISTS "PredefinedCompany_name_key" ON "PredefinedCompany"("name");

-- Insert initial workers
INSERT OR IGNORE INTO "PredefinedWorker" ("id", "name", "createdAt", "updatedAt") VALUES
    ('worker_1', 'IVICA STANISAVLJEVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_2', 'IVAN STANISAVLJEVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_3', 'EMRUŠ DULJAJ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_4', 'ELMEDIN DULJAJ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_5', 'PETAR PETROVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_6', 'DRAGAN MILOSAVLJEVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_7', 'MARKO ŽIVANOVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_8', 'DEJAN MILOVANOVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_9', 'MILOŠ ĆEBIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_10', 'BOJAN TANASKOVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_11', 'DEJAN SIMIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_12', 'NIKOLA MIRKOVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_13', 'STEFAN NOVAKOVIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('worker_14', 'NEBOJŠA NIKOLIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert initial companies
INSERT OR IGNORE INTO "PredefinedCompany" ("id", "name", "createdAt", "updatedAt") VALUES
    ('company_1', 'APPROVED GREEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('company_2', 'VITOBELLO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('company_3', 'AUTO STANIĆ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('company_4', 'SELMAN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('company_5', 'TVH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('company_6', 'CRD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('company_7', 'RETTIFICHE 3G', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('company_8', 'BOLS MOTOREN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
